### ISSUE TITLE
Syntax changing

### ISSUE THREAD

**Issue by danielkupco** [danielkupco/PyMaJORME#11]
The current syntax is a bit unclear. Suggestion for new syntax is added in pymajorme/examples/syntax_example.jorm. New syntax should bring some improvements, scalability and make the code clearer.

**Comment by RadeKornjaca** [comment]
I'm fine with the changes, except for the collection type handling. I propose more elegant way of doing that by using collection types as namespaces and putting relations inside them.
For example:

```
relations as list {
    Entity1 -> Entity2
    Entity3 <-> Entity4
    Entity4 -- Entity2
}
```

Note that 1:1 relations aren't affected by this, but they could optionally be part of this namespacing.

**Comment by danielkupco** [comment]
Syntax has been changed. Eventually, entities and relations will be structured similarly.
