### ISSUE TITLE
CLI for PyMaJORME

### ISSUE THREAD

**Issue by danielkupco** [danielkupco/PyMaJORME#5]
PyMaJORME module should work as a simple CLI application.
CLI framework of choice is [Click](http://click.pocoo.org/5/) because it is very simple yet powerful and configurable.

**Comment by RadeKornjaca** [comment]
CLI options suggestion:

-a, --all, use all of the generators (entity, Dao etc.)
-e, --entity, generate only entities
-d, --dao, generate Dao and entities (there's no much of a purpose in generating Dao alone)

**Comment by danielkupco** [comment]
Agreed. Nice and simple.

Maybe you could leave generating only Dao, because of consistency, a possibility of argument combinations and because you never know what a user may need.

-c, --config, could be user for generating only configuration file(s).

Also, a path/name to a user's '.jorm' file could be added as an argument or an answer to a console prompt, so a model from that file can be read.

**Comment by RadeKornjaca** [comment]
CLI (for now) is:

-a, --all, use all of the generators (entity, Dao etc.)
-e, --entity, generate only entities
-d, --dao, generate Dao layer
-r, --root, to specify whereby generated classes will have root directory or not
